[Definition]
datepattern = "time":"%%ExY-%%m-%%dT%%H:%%M:%%S(?:\.%%f)?%%z"
failregex = ^.*"ClientHost":"<HOST>".*"RequestHost":"portal\.catuc\.zingersystems\.com".*"DownstreamStatus":401.*$
            ^.*"ClientHost":"<HOST>".*"DownstreamStatus":401.*"RequestHost":"portal\.catuc\.zingersystems\.com".*$
ignoreregex =
